### ISSUE TITLE
Issue with HA core 2021.4.4?

### ISSUE THREAD

**Issue by Yonny24** [nick2525/broadlink_s1c_s2c#3]
Hi.

I just tried up update to the latest HA core and broadlink entities failed to load. 
Rolled back to 2021.3.4 and working again.

Are you aware of any known breaking changes yet? Maybe too early to say?

Thanks

**Comment by PcOnline2004** [comment]
Me still works.

**Comment by nick2525** [comment]
It was fixed

**Comment by PcOnline2004** [comment]
I get the same with door sensor. Changed the template code for binary_sensor would be OK.

**Comment by nick2525** [comment]
@PcOnline2004 can you post yaml here, how you changed template code.
