### ISSUE TITLE
Issue with 'unknown' status even though the app says 'person detected'

### ISSUE THREAD

**Issue by Yonny24** [nick2525/broadlink_s1c_s2c#7]
Hi. I have 2 pir sensors with the S1c alarm hub. Up until recently, this integration has been working brilliantly thanks.

I've come across an issue with one of my pir sensors where the tamper switch is stuck, 
So in HA I either get 'tampered' status or 'unknown'

But in the app when I pass motion across the sensor I do see 'person detected'.

Could it be in your coding somewhere that it is returning 'unknown' due to the tampered switch constantly on?
It changes from 'tampered' to 'unknown' when I pass my hand across the sensor.

Any hack to ignore the tampered status and return motion-detected?

Thanks

**Comment by Yonny24** [comment]
Hacked by soldering in a jumper across the tamper switch for now

**Comment by nick2525** [comment]
@Yonny24 The main thing is that you yourself have enough of those states that the sensors return. You can rename, for example, the unknown state through the sensor template, as was done when solving this bug https://github.com/nick2525/broadlink_s1c_s2c/issues/4
